server:
  port: 8080
spring:
  application:
    name: gmd #\u8FD9\u4E2A\u914D\u7F6E\u5728\u5355\u4F53\u9879\u76EE\u4E2D\u7528\u7684\u4E0D\u591A\u3002\u4E0D\u914D\u4E5F\u53EF\u4EE5\u3002\u4F46\u662F\u5728\u5206\u5E03\u5F0F\u9879\u76EE\u4E2D\u662F\u5FC5\u987B\u8981\u914D\u7F6E\u7684\u3002
  freemarker:
    suffix: .ftlh
    settings:
      number_format: 0.##
    cache: false
    charset: UTF-8
    content-type: text/html;charset=utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geng?useEncoding=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.gmd.entity

logging:
  level:
    cn:
      edu:
        sudt:
          springbootmybatisfreemarkerdemo:
            mapper: debug
